CREATE TABLE DISH
(
    ID           BIGINT PRIMARY KEY NOT NULL auto_increment,
    PRICE        DOUBLE             NOT NULL,
    TITLE_RU     VARCHAR(255)       NOT NULL,
    TITLE_EN     VARCHAR(255)       NOT NULL,
    FK_CAFE_ID BIGINT             NOT NULL,
    DESCRIPTION  VARCHAR(1024),
    FK_IMAGE_ID  BIGINT
);
CREATE TABLE CATEGORY
(
    ID       BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TITLE_RU VARCHAR(128)       NOT NULL,
    TITLE_EN VARCHAR(128)       NOT NULL
);

CREATE TABLE CAFE
(
    ID          BIGINT PRIMARY KEY NOT NULL auto_increment,
    NAME        VARCHAR(128)       NOT NULL,
    FK_IMAGE_ID BIGINT
);
CREATE TABLE CAFE_IMAGE
(
    ID    BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IMAGE VARCHAR(255)

);
CREATE TABLE DISH_IMAGE
(
    ID    BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IMAGE VARCHAR(255)

);
CREATE TABLE BASKET
(
    ID         BIGINT PRIMARY KEY NOT NULL auto_increment,
    FK_USER_ID BIGINT             NOT NULL
);
CREATE TABLE ROLE
(
    ID    BIGINT PRIMARY KEY NOT NULL auto_increment,
    TITLE VARCHAR(128)       NOT NULL
);
CREATE TABLE USER
(
    ID           BIGINT PRIMARY KEY NOT NULL auto_increment,
    EMAIL        VARCHAR(128)       NOT NULL,
    ACTIVE       SMALLINT           NOT NULL,
    USERNAME     VARCHAR(128)       NOT NULL,
    PASSWORD     VARCHAR(60)        NOT NULL,
    FK_ROLE_ID   BIGINT             NOT NULL,
    FK_BASKET_ID BIGINT
);
CREATE TABLE dish_with_category
(
    dish_id     bigint not null,
    category_id bigint not null
);

ALTER TABLE dish_with_category
    add FOREIGN KEY (dish_id) references dish (id);
ALTER TABLE dish_with_category
    add FOREIGN KEY (category_id) references CATEGORY (id);
ALTER TABLE dish
    add foreign key (fk_image_id) references DISH_IMAGE (ID);
ALTER TABLE dish
    ADD FOREIGN KEY (FK_CAFE_ID) REFERENCES CAFE (ID);
ALTER TABLE CAFE
    ADD FOREIGN KEY (FK_IMAGE_ID) REFERENCES CAFE_IMAGE (ID);


ALTER TABLE BASKET
    ADD FOREIGN KEY (FK_USER_ID) REFERENCES USER (ID);
ALTER TABLE USER
    ADD FOREIGN KEY (FK_ROLE_ID) REFERENCES ROLE (ID);
ALTER TABLE USER
    ADD FOREIGN KEY (FK_BASKET_ID) REFERENCES BASKET (ID);
